### PR TITLE
Add link for SSO authentication

### PR DESCRIPTION
**Pull request by ar-jan**

### CODE REVIEW

**Comment by tymees** [comment]
Because nobody picked this up;

The link you added is already present in the step above, so this seems redundant?

**Comment by ar-jan** [comment]
Normally it should be redundant yes, the reason for the PR was that after doing step 3 you're automatically prompted to do 4. If you don't complete this or dismiss it you're connected the the org but unauthenticated, and GitHub doesn´t prompt you again. This just makes explicit that in that case you can visit the sso URL again to authenticate.

**Comment by tymees** [comment]
Hmmm, I'm confused.

From what I can tell, step 4 is actually _meant_ as part of step 3. (Click this link (3) and log in there (4)). The issue you describe seems to imply that after that, you need to login again? Weird behaviour....

In any case, GitHub will prompt you 100 times to authenticate if you are not currently authenticated, so I'm not sure this is entirely necessary; and in this form it's also a bit confusing (as 4 is not meant to be a generic 'log in here' step). 

A better way might be adding a text after those steps:
> GitHub will require you to re-authenticate using your Solis-ID periodically. Either click the link when GitHub prompts you, or authenticate [using this link](https://github.com/orgs/CentreForDigitalHumanities/sso).

**Comment by tymees** [comment]
Paging @73616e646572 to weigh in ;)

**Comment by ar-jan** [comment]
I think it's fine to close this, if you just complete the login after step 3 all's good. And yes GitHub will prompt again later, but that could be hours or next day. So in my case I became a member of the org, but couldn't see any non-public repos (going by memory here, it's been a while). I was looking to trigger the sso again, and it wasn't immediately clear to me how to do that.

**Comment by tymees** [comment]
If closing this is fine with you, I'll do that now.

It's still a hypothetical problem, but I doubt it's going to be a huge problem. (Especially as it's a one time thing, and most people arrive by invite lately)

**Pull request closed without merging**
